const UserDB = require('../database/UserDB');
const client = require('../twilio/client');
const customError = require('../utils/customError');
const io = require('../../../io');

/**
 *
 * @param {Call} data - the call data for the incoming call
 * @param {String} fromPhoneNumber - phoneNumber extracted from the data.To property
 * @param {String} accountSid - the account sid for twilio phoneNumber
 * @returns {twiml} - generated by client.incomingCall || null if error
 */
const incomingCall = async (data, fromPhoneNumber, accountSid) => {
	try {
		const toUserId = await UserDB.findUserByAccountSid(accountSid);

		if (!toUserId) {
			customError.throwCustomError(404, 'User not found');
		}

		// Determine if the caller belongs to the logged in users contact and show the name
		const contacts = await UserDB.getUserContacts(toUserId);

		let callerName =
			contacts.filter((contact) => {
				return contact.phoneNumber === fromPhoneNumber;
			})[0]?.nickname || fromPhoneNumber;

		return client.incomingCall(data, callerName, toUserId);
	} catch (err) {
		console.log(err.message);
		return null;
	}
};

const getCallToken = (req, res) => {
	client.getCallToken(req, res);
};

/**
 * Parse the users response to incoming call and redirect to the
 * proper client handler
 * @param {String} callSid
 * @param {String} response - the users response to the incoming call event
 * @returns {undefined}
 */
const callResponse = (callSid, response) => {
	switch (response) {
		case 'accept':
			client.answerCall(callSid);
			break;

		case 'reject':
			client.declineCall(callSid);
			break;

		case 'drop':
			client.endCall(callSid);
			break;

		default:
			return;
	}
};

/**
 * Will extract @var phoneNumber from user and make client do an outbound call
 * @param {String} to - phone number to be called
 * @param {String} userId - id of the user making the call
 */
const outboundCall = async (to, userId) => {
	const user = await UserDB.findExistingUserById(userId);

	if (!user) {
		customError.throwCustomError(404, 'User not found');
	}

	const from = '+' + user.phoneNumber;

	return await client.outboundCall(to, from);
};

/**
 * Parse the call status to update the front-end
 * @param {Call} callData - the details of the call generated by twilio
 */
const callUpdate = async (callData) => {
	const user = await UserDB.findUserByAccountSid(callData.AccountSid);

	if (!user) {
		return;
	}

	switch (callData.CallStatus) {
		case 'busy':
			io.emit('call declined', { status: 'Call Declined', userId: user._id });
			break;
		case 'no-answer':
			io.emit('call declined', { status: 'No Answer', userId: user._id });
			break;
		case 'failed':
			io.emit('call declined', { status: 'Call Failed', userId: user._id });
			break;
		case 'completed':
			io.emit('call status', { status: 'Call Completed', userId: user._id });
			break;
		case 'ringing':
			io.emit('call status', { status: 'Ringing', userId: user._id });
			break;
		case 'answered':
			io.emit('call status', { status: 'Call in progress', userId: user._id });
			break;
		case 'in-progress':
			io.emit('call status', { status: 'Call in progress', userId: user._id });
			break;
		default:
			return;
	}
};

module.exports = {
	incomingCall,
	getCallToken,
	callResponse,
	outboundCall,
	callUpdate,
};
